//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _4333Project
{
    using System;
    using System.Collections.Generic;
    
    public partial class Clients
    {
        public int ID { get; set; }
        public string FullName { get; set; }
        public string ClientCode { get; set; }
        public System.DateTime BirthDate { get; set; }
        public string PostalCode { get; set; }
        public string City { get; set; }
        public string Street { get; set; }
        public string House { get; set; }
        public string Apartment { get; set; }
        public string Email { get; set; }
    }
}
